#!/usr/bin/env bash
set -Eeuo pipefail

ENV_NAME="${ENV_NAME:-aloha}"
ACT_ROOT="${ACT_ROOT:-$HOME/lmy/act}"
PROJECT_DIR="${PROJECT_DIR:-$ACT_ROOT/ACT-plus-plus}"
WHEEL_DIR="${WHEEL_DIR:-$ACT_ROOT/cu130}"
CONDA_HOME="${CONDA_HOME:-$HOME/miniconda3}"
ROS_SETUP="${ROS_SETUP:-/opt/ros/jazzy/setup.bash}"
PYTHON_VERSION="${PYTHON_VERSION:-3.12}"
RECREATE=0
SKIP_VERIFY=0
VERIFY_ONLY=0

usage() {
    cat <<EOF
Usage: $(basename "$0") [options]

Create and verify the F1 ACT runtime environment.

Options:
  --recreate       Remove and recreate the Conda environment.
    --verify-only    Do not install; verify the existing environment and model.
  --skip-verify    Install only; skip import, CUDA, model-load and dry-run checks.
  --env NAME       Conda environment name (default: aloha).
  --help           Show this help.

Environment overrides:
  ACT_ROOT, PROJECT_DIR, WHEEL_DIR, CONDA_HOME, ROS_SETUP, PYTHON_VERSION
EOF
}

while (($#)); do
    case "$1" in
        --recreate) RECREATE=1 ;;
        --verify-only) VERIFY_ONLY=1 ;;
        --skip-verify) SKIP_VERIFY=1 ;;
        --env)
            [[ $# -ge 2 ]] || { echo "--env requires a value" >&2; exit 2; }
            ENV_NAME="$2"
            shift
            ;;
        --help|-h) usage; exit 0 ;;
        *) echo "Unknown option: $1" >&2; usage >&2; exit 2 ;;
    esac
    shift
done

log() { printf '\n==> %s\n' "$*"; }
die() { echo "ERROR: $*" >&2; exit 1; }

((VERIFY_ONLY == 0 || RECREATE == 0)) || die "--verify-only and --recreate cannot be used together."
((VERIFY_ONLY == 0 || SKIP_VERIFY == 0)) || die "--verify-only and --skip-verify cannot be used together."

[[ "$(uname -m)" == "aarch64" ]] || die "This deployment targets aarch64; found $(uname -m)."
[[ -f "$PROJECT_DIR/requirements_f1_runtime.txt" ]] || die "Missing $PROJECT_DIR/requirements_f1_runtime.txt"
[[ -f "$WHEEL_DIR/torch-2.10.0-cp312-cp312-linux_aarch64.whl" ]] || die "Missing Torch wheel in $WHEEL_DIR"
[[ -f "$WHEEL_DIR/torchvision-0.25.0-cp312-cp312-linux_aarch64.whl" ]] || die "Missing Torchvision wheel in $WHEEL_DIR"
[[ -f "$ROS_SETUP" ]] || die "ROS 2 Jazzy not found: $ROS_SETUP"
[[ -e /usr/local/cuda/targets/sbsa-linux/lib/libcudart.so.13 ]] || die "CUDA 13 runtime not found."

if [[ ! -x "$CONDA_HOME/bin/conda" ]]; then
    INSTALLER="$ACT_ROOT/Miniforge3-Linux-aarch64.sh"
    [[ -f "$INSTALLER" ]] || die "Conda not found and installer is missing: $INSTALLER"
    log "Installing Miniforge into $CONDA_HOME"
    bash "$INSTALLER" -b -p "$CONDA_HOME"
fi

# shellcheck disable=SC1091
source "$CONDA_HOME/etc/profile.d/conda.sh"

if ((VERIFY_ONLY)); then
    conda env list | awk '{print $1}' | grep -Fxq "$ENV_NAME" || die "Environment does not exist: $ENV_NAME"
elif conda env list | awk '{print $1}' | grep -Fxq "$ENV_NAME"; then
    if ((RECREATE)); then
        log "Removing existing environment $ENV_NAME"
        conda deactivate 2>/dev/null || true
        conda env remove -n "$ENV_NAME" -y
    else
        log "Reusing existing environment $ENV_NAME"
    fi
fi

if ! conda env list | awk '{print $1}' | grep -Fxq "$ENV_NAME"; then
    log "Creating clean environment $ENV_NAME (Python $PYTHON_VERSION)"
    conda create -n "$ENV_NAME" "python=$PYTHON_VERSION" pip -y
fi

set +u
conda activate "$ENV_NAME"
set -u
[[ "$(python -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')" == "3.12" ]] || \
    die "The supplied Torch wheels require Python 3.12. Re-run with --recreate."

if ((VERIFY_ONLY == 0)); then
    log "Installing NVIDIA Thor Torch wheels"
    python -m pip install --upgrade --force-reinstall \
        "$WHEEL_DIR/torch-2.10.0-cp312-cp312-linux_aarch64.whl" \
        "$WHEEL_DIR/torchvision-0.25.0-cp312-cp312-linux_aarch64.whl"

    log "Installing minimal F1 ACT runtime dependencies"
    python -m pip install --upgrade -r "$PROJECT_DIR/requirements_f1_runtime.txt"
    # The cuDSS wheel incorrectly declares a cuda-toolkit Python dependency.
    # F1 supplies CUDA 13 system libraries, so deliberately install without it.
    python -m pip install --upgrade --no-deps nvidia-cudss-cu13==0.7.1.6

    # DETR is imported directly from the project package; editable installation
    # is retained for scripts launched outside PROJECT_DIR.
    python -m pip install --no-deps -e "$PROJECT_DIR/detr"
fi

ENV_PREFIX="$(python -c 'import sys; print(sys.prefix)')"
HOOK_DIR="$ENV_PREFIX/etc/conda/activate.d"
mkdir -p "$HOOK_DIR"
cat > "$HOOK_DIR/f1_runtime.sh" <<EOF
# Generated by $PROJECT_DIR/deploy_f1_env.sh
if [[ -f "$ROS_SETUP" ]]; then
    set +u
    source "$ROS_SETUP"
    set -u
fi
_CUDSS_LIB="\${CONDA_PREFIX}/lib/python3.12/site-packages/nvidia/cu13/lib"
_CUDA_LIB="/usr/local/cuda/targets/sbsa-linux/lib"
export LD_LIBRARY_PATH="\${_CUDSS_LIB}:\${_CUDA_LIB}:\${LD_LIBRARY_PATH:-}"
unset _CUDSS_LIB _CUDA_LIB
EOF
# Apply the hook to this process too.
# shellcheck disable=SC1090
source "$HOOK_DIR/f1_runtime.sh"

if ((SKIP_VERIFY)); then
    log "Installation complete (verification skipped)"
    exit 0
fi

log "Verifying Python, CUDA and ROS 2"
python - <<'PY'
import cv2
import numpy as np
import rclpy
import torch
import torchvision
from control_msgs.msg import GripperCommand
from sensor_msgs.msg import CompressedImage, JointState

assert torch.cuda.is_available(), "CUDA is unavailable"
x = torch.randn(128, 128, device="cuda")
y = x @ x
assert torch.isfinite(y).all(), "CUDA computation returned non-finite values"
print("Python/CUDA/ROS PASS")
print("torch:", torch.__version__, "torchvision:", torchvision.__version__)
print("numpy:", np.__version__, "opencv:", cv2.__version__)
print("GPU:", torch.cuda.get_device_name(0))
PY

log "Compiling deployment sources"
cd "$PROJECT_DIR"
python -m py_compile \
    f1_ACT_simple.py policy.py constants.py detr/initmain.py \
    detr/models/*.py detr/util/*.py

CKPT_DIR="${CKPT_DIR:-$PROJECT_DIR/fold_clothes_f1}"
if [[ -f "$CKPT_DIR/policy_best.ckpt" && -f "$CKPT_DIR/config.pkl" && -f "$CKPT_DIR/dataset_stats.pkl" ]]; then
    log "Verifying ACT checkpoint load"
    CKPT_DIR="$CKPT_DIR" python - <<'PY'
import os
import torch
from f1_ACT_simple import load_policy, load_stats

path = os.environ["CKPT_DIR"]
device = torch.device("cuda")
policy, config = load_policy(path, "policy_best.ckpt", device)
stats = load_stats(path, device)
assert config["num_queries"] == 60
assert all(tuple(stats[k].shape) == (16,) for k in stats)
print("ACT checkpoint PASS:", type(policy).__name__, "queries:", config["num_queries"])
PY

    if ros2 topic list 2>/dev/null | grep -Fxq /hal/joint_states; then
        log "Running safe live dry-run (no commands are published)"
        python f1_ACT_simple.py \
            --ckpt_dir "$CKPT_DIR" \
            --task_name fold_clothes_f1 \
            --dry_run
    else
        log "ROS graph is not active; live sensor dry-run skipped"
    fi
else
    log "Checkpoint bundle not found; checkpoint verification skipped: $CKPT_DIR"
fi

log "F1 ACT environment deployment completed successfully"
